name: second workflow
on:
  workflow_run: 
    workflows: [balnk]
    types: 
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        run: echo "deploying"
